# Generated by Django 4.0.6 on 2022-07-08 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('post', 'POST'), ('put', 'PUT'), ('get', 'GET'), ('delete', 'DELETE'), ('patch', 'PATCH')], default='get', max_length=20)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UrlSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_set', models.ManyToManyField(to='url_app.url')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
